### PR TITLE
Relation reference builder configuration closes #32

### LINKED ISSUE #32: Relation reference builder configuration
Currently there is some support for building custom relations and references, but it lacks
- A concise and easy to use API
- Documentation
- Examples
- Setter methods for some ReferenceBuilder implementations

Some attempts at building a custom relation failed misserably:
```php
    // This one only seems able to read the relation, not store it
    public function parameter(): Relations\Many
    {
        /** @var Relations\Many $relation */
        $relation = $this->relations()->get('hasManyParameter', function () {
            $key = new RemoteKey(
                new NeatProperty(new \ReflectionProperty(self::class, 'id')),
                new NeatProperty(new \ReflectionProperty(PropertyOptionParameter::class, 'optionId')),
                'option_id',
                PropertyOptionParameter::repository()
            );

            return new Relations\Many($key, $this);
        });
    }

    // This one doesn't work either
    public function parameter(): Relations\Many
    {
        return $this->buildHasMany(PropertyOptionParameter::class, 'hasManyParameter')
            ->referenceFactory(function (\Neat\Object\Relations\Reference\RemoteKeyBuilder $builder) {
                $builder->property(PropertyOptionParameter::class, 'optionId');
            })
            ->resolve();
    }
```

### PR DESCRIPTION
**Pull request by annavanbiemen**

### CODE REVIEW

File: classes/ReferenceFactory.php [hunk 1]
```diff
@@ -15,95 +15,126 @@ trait ReferenceFactory
...
+     * @psalm-param callable(JunctionTableBuilder)|null $configure
      * @return JunctionTable
      */
-    public function junctionTable(string $local, string $remote): JunctionTable
+    public function junctionTable(string $local, string $remote, callable $configure = null): JunctionTable
     {
         /** @var JunctionTable $reference */
-        $reference = $this->buildJunctionTable("{$local}junctionTable{$remote}", $local, $remote)->resolve();
+        $reference = $this->buildJunctionTable("{$local}junctionTable{$remote}", $local, $remote,
+            $configure)->resolve();
```
Comment (baukevdw) [inline classes/ReferenceFactory.php:112]: Arguments should be all on the same line or all on their own line.

File: classes/Relations/Reference/Builder.php [hunk 2]
```diff
@@ -99,6 +122,125 @@ public function setClass(string $class): self
...
+        return $this;
+    }
+
+    /**
+     * @param Property|string $localKeyProperty
+     * @return $this
+     */
+    public function setLocalKey($localKeyProperty): self
+    {
+        if (!$localKeyProperty instanceof Property) {
```
Comment (baukevdw) [inline classes/Relations/Reference/Builder.php:156]: We might want to deprecate the ability to pass a property object.

File: classes/ReferenceFactory.php (hunk 1 above)
Comment (baukevdw) [inline classes/ReferenceFactory.php]: Arguments should be all on the same line or all on their own line.

File: readme.md [hunk 3]
```diff
@@ -165,6 +165,100 @@ $user->store();
...
+    }
+
+    public function updatedBy(): Neat\Object\Relations\One
+    {
+        return $this->belongsToOne(User::class, 'updater');
+    }
+}
+```
+
+## References
```
Comment (Bloemkoolsaus) [inline readme.md:194]: Readme is inconsistent:

- Appointment model is missing it's primary key.
- The User relation remote key is not defined anywhere (`alternativeId`)

**Review by Bloemkoolsaus — APPROVED** [review]

File: classes/ReferenceFactory.php (hunk 1 above)
Comment (annavanbiemen) [reply classes/ReferenceFactory.php]: Fixed code format and return result without assignment in between.

File: readme.md (hunk 3 above)
Comment (annavanbiemen) [reply readme.md:194]: Fixed examples, inconsistencies and inspections in readme.md and readme.php

File: classes/Relations/Reference/Builder.php (hunk 2 above)
Comment (annavanbiemen) [reply classes/Relations/Reference/Builder.php:156]: Deprecation added to changelog.md and implemented by removal of Property from the @param tag of both setLocalKey and setRemoteKey. A proper IDE will start warning you about passing a Property instance.

trigger_error('...', E_USER_DEPRECATED) is a little risky since I'd like to release this within the 0.11 minor version line.
