### PR TITLE
Fix type hints, closes #31

### LINKED ISSUE #31: Add object and void type-hints
Since we dropped support for PHP <7.2 we can add the object and void type-hints where applicable.

### PR DESCRIPTION
**Pull request by annavanbiemen**
Add type hints whenever possible

### CODE REVIEW

File: classes/Decorator/EventDispatcher.php [hunk 1]
```diff
@@ -86,7 +86,7 @@ private function dispatch(string $class, object $entity): void
     /**
      * @inheritDoc
      */
-    public function load($entity)
+    public function load(object $entity)
```
Comment (baukevdw) [inline classes/Decorator/EventDispatcher.php:89]: This should return an `object` right?

File: classes/RepositoryInterface.php [hunk 2]
```diff
@@ -111,50 +111,50 @@ public function insert(array $data);
...
      */
-    public function update($id, array $data);
+    public function update($id, array $data): int;
 
     /**
      * @param object $entity
      * @return mixed
      */
-    public function load($entity);
+    public function load(object $entity);
```
Comment (baukevdw) [inline classes/RepositoryInterface.php:120]: Same as for the EventDispatcherDecorator, the Repository class does have a object return type.

**Review by baukevdw — CHANGES_REQUESTED** [review]

**Review by baukevdw — APPROVED** [review]
